homework 3
Klish132/qt-project pull request #1
Opened 2020-03-27 16:13 UTC by Klish132

2020-03-28 17:24 UTC, tugolukovpn commented on Lection2/.gitignore
> +# This file is used to ignore files which are generated
Шикарный readme file!

2020-03-28 17:24 UTC, tugolukovpn commented on Lection2/main.qml
> +    property int instance: 1
Название переменной нужно более информативное. Например, "currentForm" типа string, значения которой будут или "login_form" или "registration_form".

2020-03-28 17:24 UTC, tugolukovpn commented on Lection2/qml/signinloader.qml
> +            id: signInField1
Использовать такие названия переменных - это моветон. Каждое текстовое поле нужно для чего-то. ID должен четко показывать, что для чего нужно это текстовое поле. 
В данном случае у тебя это поле ввода логина. Т.о. можно назвать его "textFieldLogin", так будет гораздо понятнее.
Надо посмотреть id-шники во всем qml-коде и поменять, где надо.

2020-03-28 17:24 UTC, tugolukovpn commented on Lection3/AuthManager.cpp
> +        onAuthFinished();
Данная лямбда - это уже обработчик твоего запроса. Не нужно в лябмде вызывать еще один обработчик. Он просто не нужен. Соответственно, либо к сигналу финиша запроса ты подключаешь лябмду, и делаешь все дела в ней. Либо К сигналу подключаешь слот, и все дела делаешь в нем. А так получается, что у тебя отдельная функция нужна что бы испустить сигнал о финише загрузки. Это излишне. Сигнал можно испустить и из самой лямбды.

2020-03-28 17:24 UTC, tugolukovpn commented on Lection3/AuthManager.cpp
> +
Пустая строка.

2020-03-28 17:24 UTC, tugolukovpn commented on Lection3/AuthManager.cpp
> +    //qDebug() << "Auth error: " << getAuthError();
Закомментированный код нужно удалить.

2020-03-28 17:24 UTC, tugolukovpn commented on Lection3/AuthManager.cpp
> +        onRegFinished();
Тоже самое, что и про обработчик финиша запросы выше.

2020-03-28 17:24 UTC, tugolukovpn commented on Lection3/AuthManager.cpp
> +
Пустые строки, нужно удалить.

2020-03-28 17:24 UTC, tugolukovpn commented on Lection3/AuthManager.h
> +
Лишние пустые строки. Нужно удалить.

2020-03-28 17:24 UTC, tugolukovpn commented on Lection3/AuthManager.cpp
> +    QUrl url("http://127.0.0.1:58721/register");
Т.к. у тебя используется подход с сохранением ошибки и токена - если выполнить два запроса друг за другом, первый закончится с ошибкой, а второй будет успешен, что пользователь класса подумает, что у тебя ошибка все равно есть, т.к. ты не очищаешь поля с ошибками перед началом нового запроса. Так же необходимо очищать поле с  токеном перед стартом авторизации.

2020-03-29 23:28 UTC, Klish132 commented on Lection3/AuthManager.cpp
> +    QUrl url("http://127.0.0.1:58721/register");
Написал resetState(), который сбрасывает ошибки и токен перед запросом.

2020-03-29 23:28 UTC, Klish132 commented on Lection3/AuthManager.h
> +
Исправил пустые строки во всем коде.

2020-03-29 23:28 UTC, Klish132 commented on Lection3/AuthManager.cpp
> +
Исправил пустые строки во всем коде.

2020-03-29 23:28 UTC, Klish132 commented on Lection3/AuthManager.cpp
> +        onRegFinished();
Исправил.

2020-03-29 23:28 UTC, Klish132 commented on Lection3/AuthManager.cpp
> +    //qDebug() << "Auth error: " << getAuthError();
Исправил везде.

2020-03-29 23:28 UTC, Klish132 commented on Lection3/AuthManager.cpp
> +
Исправил пустые строки во всем коде.

2020-03-29 23:29 UTC, Klish132 commented on Lection3/AuthManager.cpp
> +        onAuthFinished();
Исправил, убрал слоты, сигнал теперь вызывается в лямбде.

2020-03-29 23:29 UTC, Klish132 commented on Lection2/qml/signinloader.qml
> +            id: signInField1
Исправил во всем коде.

2020-03-29 23:29 UTC, Klish132 commented on Lection2/main.qml
> +    property int instance: 1
Исправил, теперь currentWindowState.

2020-03-29 23:29 UTC, Klish132 commented on Lection2/.gitignore
> +# This file is used to ignore files which are generated
Исправил, написал небольшое описание репы.

2020-04-01 12:02 UTC, mashinapetro commented on Lection2/qml/signinloader.qml
> +            id: loginTextField
Just comment - если есть хороший id, то коммент выше не нужен. И так понятно, зачем нужен этот объект.

2020-04-01 12:06 UTC, mashinapetro requested changes

2020-04-01 12:06 UTC, mashinapetro commented on Lection3/AuthManager.cpp
> +        emit authRequestCompleted(getAuthError(), this->token);
Функция getAuthError()  возвращает значение поля класса. Зачем? Ведь прямо в этой лябмде можно получить значение ошибки и отправить ее в сигнале.

2020-04-01 12:06 UTC, mashinapetro commented on Lection3/AuthManager.h
> +    QString getAuthError();
Зачем этот метод, если  сигнал authRequestCompleted уже передает ошибку?

2020-04-01 12:06 UTC, mashinapetro commented on Lection3/AuthManager.h
> +    QString getRegisterError();
Зачем этот метод, если сигнал regRequestCompleted уже передает ошибку?

2020-04-01 12:06 UTC, mashinapetro commented on Lection3/AuthManager.h
> +private slots:
Если секция 'private slots' пустая, то ее можно удалить.

2020-04-01 12:07 UTC, mashinapetro commented on Lection3/AuthManager.cpp
> +    QUrl url("http://127.0.0.1:58721/register");
OK.

2020-04-01 12:07 UTC, mashinapetro commented on Lection3/AuthManager.h
> +
OK.

2020-04-01 12:07 UTC, mashinapetro commented on Lection3/AuthManager.cpp
> +
OK.

2020-04-01 12:07 UTC, mashinapetro commented on Lection3/AuthManager.cpp
> +        onRegFinished();
OK.

2020-04-01 12:07 UTC, mashinapetro commented on Lection3/AuthManager.cpp
> +    //qDebug() << "Auth error: " << getAuthError();
OK.

2020-04-01 12:07 UTC, mashinapetro commented on Lection3/AuthManager.cpp
> +
OK.

2020-04-01 12:07 UTC, mashinapetro commented on Lection3/AuthManager.cpp
> +        onAuthFinished();
OK.

2020-04-01 12:07 UTC, mashinapetro commented on Lection2/qml/signinloader.qml
> +            id: signInField1
OK.

2020-04-01 12:07 UTC, mashinapetro commented on Lection2/main.qml
> +    property int instance: 1
OK.

2020-04-01 12:07 UTC, mashinapetro commented on Lection2/.gitignore
> +# This file is used to ignore files which are generated
OK.

2020-04-03 09:11 UTC, Klish132 commented on Lection2/qml/signinloader.qml
> +            id: loginTextField
Я оставлю комменты, если вы не против. Мне так проще на код смотреть

2020-04-03 09:11 UTC, Klish132 commented on Lection3/AuthManager.cpp
> +        emit authRequestCompleted(getAuthError(), this->token);
Исправил.

2020-04-03 09:12 UTC, Klish132 commented on Lection3/AuthManager.h
> +    QString getAuthError();
Убрал оба метода.

2020-04-03 09:12 UTC, Klish132 commented on Lection3/AuthManager.h
> +    QString getRegisterError();
Убрал оба метода.

2020-04-03 09:12 UTC, Klish132 commented on Lection3/AuthManager.h
> +private slots:
Удалил.

2020-04-03 09:48 UTC, mashinapetro commented on Lection3/AuthManager.cpp
> +        emit authRequestCompleted(getAuthError(), this->token);
Ок.

2020-04-03 09:48 UTC, mashinapetro commented on Lection2/qml/signinloader.qml
> +            id: loginTextField
Ок.

2020-04-03 09:49 UTC, mashinapetro commented on Lection3/AuthManager.h
> +    QString getAuthError();
Ок.

2020-04-03 09:49 UTC, mashinapetro commented on Lection3/AuthManager.h
> +private slots:
Ок.

2020-04-03 09:50 UTC, mashinapetro requested changes

2020-04-03 09:50 UTC, mashinapetro commented on Lection3/AuthManager.h
> +    void resetState();
Метод resetState используется только внутри класса, значит должен быть приватным.

2020-04-03 09:50 UTC, mashinapetro commented on Lection3/AuthManager.h
> +    QString getToken();
Этот метод не нужен, т.к. токен передается в сигнале.

2020-04-03 09:50 UTC, mashinapetro commented on Lection3/AuthManager.h
> +    QString registerError;
Зачем нужны эти три строковые переменные?

2020-04-03 10:07 UTC, Klish132 commented on Lection3/AuthManager.h
> +    void resetState();
Поменял

2020-04-03 10:07 UTC, Klish132 commented on Lection3/AuthManager.h
> +    QString getToken();
Убрал

2020-04-03 10:09 UTC, Klish132 commented on Lection3/AuthManager.h
> +    QString registerError;
Не понял, про какие три вы говорите? Я убрал 2 переменные ошибок, но токен не убирать не нужно, ведь в условии задачи нужно поле класса для токена?

2020-04-03 10:11 UTC, mashinapetro commented on Lection3/AuthManager.h
> +    QString getToken();
Ноуп, не нужен. Договорились, что будем все данные передавать в сигналах.

2020-04-03 10:29 UTC, mashinapetro requested changes

2020-04-03 10:29 UTC, mashinapetro commented on Lection3/AuthManager.h
> +    QString token;
Это поле класса нигде не используется. Надо удалить.

2020-04-03 11:14 UTC, mashinapetro approved these changes

2020-04-03 12:09 UTC, merged